name: Build iOS IPA
on:
  # Enable manual run
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

env:
  pkg_name: tachidesk-sorayomi

jobs:
  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: dart run build_runner build --delete-conflicting-outputs

      - name: Build iOS IPA
        run: flutter build ios --release --no-codesign

      - name: Create IPA package
        working-directory: build/ios/iphoneos
        run: |
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app-release.ipa Payload
          mv app-release.ipa "$GITHUB_WORKSPACE/${{ env.pkg_name }}-${{ github.ref_name }}-ios.ipa"

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ${{ env.pkg_name }}-${{ github.ref_name }}-ios.ipa

      - name: Add IPA to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: ${{ env.pkg_name }}-${{ github.ref_name }}-ios.ipa
          token: ${{ secrets.GITHUB_TOKEN }}
