name: Publish
on:
  # Enable manual run
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"
env:
  pkg_name: tachidesk-sorayomi
jobs:
  create-build:
    name: Create ${{ matrix.target }} build
    runs-on: ${{ matrix.os }}
    # softprops/action-gh-release needs this permission
    permissions:
      contents: write

    strategy:
      # Disable fail-fast as we want results from all even if one fails.
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: ios
            build_path: build/ios
          
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Recreating the project
      - run: flutter doctor -v
      - uses: actions/checkout@v3
      # - run: flutter create .
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: dart run build_runner build --delete-conflicting-outputs


      - if: matrix.target == 'ios'
        run: flutter build ios --release --no-codesign

      - name: Compress build for iOS
        if: matrix.target == 'ios'
        working-directory: ${{ matrix.build_path }}
        run: |
          cd iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app-release.ipa Payload
          mv app-release.ipa "$GITHUB_WORKSPACE/${{ env.pkg_name }}-${{ github.ref_name }}-${{ matrix.target }}.ipa"

      - name: Add packaged build to release draft
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: ${{ env.pkg_name }}*
          token: ${{ secrets.DEPLOY_TOKEN }}

  homebrew-cask-publish:
    needs: create-build
    runs-on: macos-latest
    steps:
      - name: Update Homebrew cask
        uses: macauley/action-homebrew-bump-cask@v1
        with:
          token: ${{secrets.WINGET}}
          tap: homebrew/homebrew-cask
          cask: tachidesk-sorayomi
          livecheck: true
